Loaded module: cuda/12.1
Downloading readme:   0%|          | 0.00/10.2k [00:00<?, ?B/s]Downloading readme: 100%|██████████| 10.2k/10.2k [00:00<00:00, 9.79MB/s]
/usr/lib64/python3.9/site-packages/scipy/__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.2)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "
Downloading data files:   0%|          | 0/2 [00:00<?, ?it/s]
Downloading data:   0%|          | 0.00/39.5M [00:00<?, ?B/s][A
Downloading data:  11%|█         | 4.19M/39.5M [00:00<00:03, 9.26MB/s][A
Downloading data:  32%|███▏      | 12.6M/39.5M [00:00<00:01, 22.1MB/s][A
Downloading data:  53%|█████▎    | 21.0M/39.5M [00:00<00:00, 29.7MB/s][A
Downloading data:  74%|███████▍  | 29.4M/39.5M [00:01<00:00, 34.3MB/s][A
Downloading data:  96%|█████████▌| 37.7M/39.5M [00:01<00:00, 37.7MB/s][ADownloading data: 100%|██████████| 39.5M/39.5M [00:01<00:00, 29.6MB/s]
Downloading data files:  50%|█████     | 1/2 [00:01<00:01,  1.35s/it]
Downloading data:   0%|          | 0.00/2.08M [00:00<?, ?B/s][A
Downloading data: 100%|██████████| 2.08M/2.08M [00:00<00:00, 13.0MB/s][ADownloading data: 100%|██████████| 2.08M/2.08M [00:00<00:00, 12.5MB/s]
Downloading data files: 100%|██████████| 2/2 [00:01<00:00,  1.52it/s]Downloading data files: 100%|██████████| 2/2 [00:01<00:00,  1.31it/s]
Extracting data files:   0%|          | 0/2 [00:00<?, ?it/s]Extracting data files: 100%|██████████| 2/2 [00:00<00:00, 149.71it/s]
Generating train split:   0%|          | 0/84437 [00:00<?, ? examples/s]Generating train split:  36%|███▌      | 30000/84437 [00:00<00:00, 174267.46 examples/s]Generating train split:  83%|████████▎ | 70000/84437 [00:00<00:00, 201242.53 examples/s]Generating train split: 100%|██████████| 84437/84437 [00:00<00:00, 114801.94 examples/s]
Generating validation split:   0%|          | 0/4401 [00:00<?, ? examples/s]Generating validation split: 100%|██████████| 4401/4401 [00:00<00:00, 120937.22 examples/s]
python3: can't open file '/tools/process_data_dolly.py': [Errno 2] No such file or directory
python3: can't open file '/tools/process_data_dolly.py': [Errno 2] No such file or directory
